id: 45f4d1851c4c407d9b88cdfda4884737
title: Toh_179-Teaching_The_Relative_and_Ultimate_Truths-v1
type: translation
source_metadata:
  creationtool: Olifant
  creationdate: 20170418T102617Z
  creationid: CloudedCat
  changedate: 20170418T103530Z
  changeid: CloudedCat
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: tei
  datatype: Text
  eft-text-id: UT22084-060-008
  eft-text-version: 2.24.2 2020
  xmlns-eft: http://read.84000.co/ns/1.0
